#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# A/B
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/launch_with_vendor_ramdisk.mk)

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_system=true \
    POSTINSTALL_PATH_system=system/bin/otapreopt_script \
    FILESYSTEM_TYPE_system=erofs \
    POSTINSTALL_OPTIONAL_system=true

AB_OTA_POSTINSTALL_CONFIG += \
    RUN_POSTINSTALL_vendor=true \
    POSTINSTALL_PATH_vendor=bin/checkpoint_gc \
    FILESYSTEM_TYPE_vendor=erofs \
    POSTINSTALL_OPTIONAL_vendor=true

PRODUCT_PACKAGES += \
    checkpoint_gc \
    otapreopt_script

# API — must match RELEASE_PLATFORM_SDK_VERSION (35 for ap3a)
# Stock device ships with SDK 36 but ap3a framework only supports up to 35.
PRODUCT_SHIPPING_API_LEVEL := 35



# Boot animation (1216x2688 from display extraction)
TARGET_SCREEN_HEIGHT := 2688
TARGET_SCREEN_WIDTH := 1216

# Dynamic partitions
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# Fastbootd
PRODUCT_PACKAGES += \
    fastbootd

# Filesystem
PRODUCT_PACKAGES += \
    fs_config_files

# Firmware (vendor blobs installed via PRODUCT_COPY_FILES in vendor mk)
$(call inherit-product-if-exists, vendor/nubia/NX809J/NX809J-vendor.mk)

# Boot control HAL — needed in recovery for OTA sideload (update_engine)
PRODUCT_PACKAGES += \
    android.hardware.boot-service.default_recovery

# Init
PRODUCT_PACKAGES += \
    fstab.qcom \
    init.NX809J.rc

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/init.recovery.qcom.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.qcom.rc

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/rootdir/etc/fstab.qcom:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.qcom

# Soong-bypass installs for orphan AIDL prebuilts.
# These are vendor .so files whose AIDL interface version is no longer
# built by AOSP source (frozen at an older version), but vendor consumer
# blobs DT_NEED them at process load. Listing them in proprietary-files.txt
# would create a Soong PART conflict (source declares the namespace name
# even when it can't build the version). PRODUCT_COPY_FILES is a Make-
# level mechanism that bypasses Soong's module system entirely.
# BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true (BoardConfig.mk)
# permits ELFs in PRODUCT_COPY_FILES.
#
# - sharedsecret-V2: source frozen at V1; libspukeymint.so DT_NEEDs V2
#   and would fail at dlopen otherwise. Source: verify_aidl_versions.py
#   KEEP entry, .aidl_verify.txt.
# - libNubiaImageAlgorithmVD: Nubia proprietary camera/image algorithm
#   library. Has no AOSP source counterpart. cc_prebuilt_library_shared
#   can't be emitted because the blob's DT_NEEDED includes libskia,
#   which only has a system variant in AOSP source — Soong fails with
#   "missing variant" when trying to build a vendor variant. Bypassing
#   Soong via PRODUCT_COPY_FILES installs the .so directly to
#   /vendor/lib64/, where any vendor process that dlopens it by name
#   will find it. (BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES allows
#   ELFs in PRODUCT_COPY_FILES.)
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/lib64/libNubiaImageAlgorithmVD.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libNubiaImageAlgorithmVD.so
# Note: sharedsecret-V2-ndk.so + libhapticgenerator.so were PCF-installed
# earlier as workarounds for Soong analysis errors. Both are now
# resolved via Soong (sharedsecret-V2 auto-generated by libspukeymint
# transitive AIDL closure; libhapticgenerator builds from
# frameworks/av/media/libeffects/hapticgenerator/). PCF copies removed
# to avoid kati duplicate-target collisions.

# SPU TEE keymint cluster — PCF bypass.
# See closure.py EXCLUDE_PATHS comment block for the full rationale.
# Soong rejects the cluster because libspukeymintprovision (statically
# linked into keymint-service-spu-qti) DT_NEEDs keymint-V2-ndk while
# the binary also DT_NEEDs keymint-V4-ndk → multi-version conflict.
# Runtime resolution from /system/lib64/ handles V2 and V4 independently.
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/lib64/libspukeymint.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspukeymint.so \
    vendor/nubia/NX809J/proprietary/vendor/lib64/libspukeymintdeviceutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspukeymintdeviceutils.so \
    vendor/nubia/NX809J/proprietary/vendor/lib64/libspukeymintprovision.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspukeymintprovision.so \
    vendor/nubia/NX809J/proprietary/vendor/lib64/libspukeymintutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspukeymintutils.so \
    vendor/nubia/NX809J/proprietary/vendor/lib64/hw/libspuqtigatekeeper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/libspuqtigatekeeper.so \
    vendor/nubia/NX809J/proprietary/vendor/bin/spu_install_keybox:$(TARGET_COPY_OUT_VENDOR)/bin/spu_install_keybox \
    vendor/nubia/NX809J/proprietary/vendor/bin/hw/android.hardware.gatekeeper-service-spu-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper-service-spu-qti \
    vendor/nubia/NX809J/proprietary/vendor/bin/hw/android.hardware.security.keymint-service-spu-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.security.keymint-service-spu-qti \
    vendor/nubia/NX809J/proprietary/vendor/bin/hw/android.hardware.weaver-service-spu-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.weaver-service-spu-qti

# Camera node plugins with multi-version DT_NEEDED — PCF bypass.
# com.qti.node.dewarp.so has BOTH graphics.allocator-V1 and -V2 NEEDED
# entries in a single binary; Soong rejects. Camera HAL loads these
# plugins by name via dlopen at runtime, no Soong link needed.
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/lib64/camera/components/com.qti.node.dewarp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.qti.node.dewarp.so

# iter 224: Critical vendor HAL binaries missing from proprietary-files.txt.
# These were excluded by closure.py due to Soong analysis conflicts but are
# required at runtime. Without these: no display, no boot control (watchdog
# reboot), no USB (no ADB), no audio, no sensors.
# Identified via pstore crash analysis: phone booted 228s then watchdog
# rebooted because sys.boot_completed never set.
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/bin/hw/android.hardware.boot-service.qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.boot-service.qti \
    vendor/nubia/NX809J/proprietary/vendor/etc/init/android.hardware.boot-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.boot-service.qti.rc \
    vendor/nubia/NX809J/proprietary/vendor/bin/hw/android.hardware.thermal-service.qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.thermal-service.qti \
    vendor/nubia/NX809J/proprietary/vendor/etc/init/android.hardware.thermal-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal-service.qti.rc

# PCF bypass for firmware-style trees that hit soong_filesystem_creator
# "Path is outside directory" or are silently dropped by extract-utils.
# See closure.py PCF_BYPASS_PATHS for the per-prefix rationale.
# firmware_pcf.mk is auto-generated; re-run closure.py to refresh.
include $(LOCAL_PATH)/firmware_pcf.mk

# Overlays
PRODUCT_PACKAGES += \
    FrameworksResNX809J

# Partitions
PRODUCT_BUILD_SUPER_PARTITION := true

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += \
    hardware/qcom-caf/sm8750 \
    hardware/qcom-caf/wlan \
    hardware/qcom-caf/wlan/qcwcn \
    vendor/qcom/opensource/commonsys-intf/display \
    external/OpenCL-ICD-Loader \
    hardware/qcom-caf/common/libqti-perfd-client \
    vendor/qcom/opensource/dataservices \
    vendor/nubia/NX809J \
    $(LOCAL_PATH)

# WiFi/qcwcn namespace import — required by hostapd and wpa_supplicant which
# depend on lib_driver_cmd_qcwcn (defined at
# hardware/qcom-caf/wlan/qcwcn/wpa_supplicant_8_lib/Android.bp:38).
# Soong namespaces are NOT recursive — importing the parent hardware/qcom-caf/wlan
# doesn't grant access to the qcwcn child namespace, even though qcwcn's
# Android.bp itself imports the parent.
#
# Verified iter 189: only one child soong_namespace exists under
# hardware/qcom-caf/wlan/ (qcwcn). No siblings to bulk-add. dodge sm8750-common
# gets this namespace from somewhere in its inheritance chain (NOT from
# hardware/qcom-caf/common/common.mk, which has zero PRODUCT_SOONG_NAMESPACES
# declarations — verified iter 189). We add it directly here.
#
# This is the downstream consequence of iter-188's wifi PRODUCT_PACKAGES
# additions. Adding hostapd/wpa_supplicant to the build graph surfaced this
# namespace gap.

# Update engine
PRODUCT_PACKAGES += \
    update_engine \
    update_engine_sideload \
    update_verifier

# VINTF compatibility matrix module
# The vintf_data{type:"device_cm"} producer is defined at
# system/libhidl/vintfdata/Android.bp:19-24, fed our static stock matrix via
# DEVICE_MATRIX_FILE in BoardConfig.mk. The producer module is named
# vendor_compatibility_matrix.xml (Soong module name, not file name).
#
# AOSP base_vendor.mk:112 lists this module in PRODUCT_PACKAGES, which is how
# devices that inherit base_vendor.mk get the matrix automatically. We don't
# inherit base_vendor.mk (it would re-add ~50 modules we've explicitly excluded
# via the closure approach), so we add this single module surgically.
#
# Without this line, the soong build rule exists, the install rule exists, the
# static input file exists, but no goal target visits the edge — ninja never
# produces vendor/etc/vintf/compatibility_matrix.xml, and checkvintf halts the
# build with NAME_NOT_FOUND. Took four iters (173, 181, 183, 184) to find this.
PRODUCT_PACKAGES += \
    vendor_compatibility_matrix.xml

# Framework VINTF modules — symmetric to vendor_compatibility_matrix.xml above.
# AOSP base_system.mk:414 lists these in PRODUCT_PACKAGES; devices that inherit
# base_system get them automatically. We don't inherit base_system (closure
# approach), so add them surgically.
#
# Without these, the OTA generator's checkvintf step fails at iter 212 with:
#   "No framework manifest file from device or from update package"
#   "No framework compatibility matrix files under /system/etc/vintf/"
# Because the SYSTEM staging dir has no etc/vintf/ contents at all.
#
# Modules:
#   system_manifest.xml — vintf_data{type:"system_manifest"} from
#     system/libhidl/vintfdata/Android.bp:26-30. Generates the framework
#     HAL manifest at /system/etc/vintf/manifest.xml
#   system_compatibility_matrix.xml — base_system.mk standard. Generates
#     the framework compatibility matrix at /system/etc/vintf/compatibility_matrix.xml
#     (assembled from DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE in BoardConfig.mk)
#
# Symmetric to iter 184's vendor_compatibility_matrix.xml fix.
PRODUCT_PACKAGES += \
    system_manifest.xml \
    system_compatibility_matrix.xml

# WiFi packages — explicit closure inclusion to fix iter-187 libwifi-hal-qcom drop
# Sourced from LineageOS device/oneplus/sm8750-common/common.mk at lineage-23.2.
# The libwifi-hal-qcom entry is the critical one; without it, the source-side
# cc_library compiles a CFI variant that doesn't match our prebuilt's plain variant,
# and Soong silently drops the dep from hal_proxy_daemon's resolved shared_libs.
# Adding to PRODUCT_PACKAGES forces the module into the goal closure (same shape
# as iter-184's vendor_compatibility_matrix.xml fix).
PRODUCT_PACKAGES += \
    android.hardware.wifi-service \
    hostapd \
    libwifi-hal-ctrl \
    libwifi-hal-qcom \
    wpa_supplicant \
    wpa_supplicant.conf

# 16 KB page size check bypass for prebuilt libraries
#
# Android 16 (Baklava) introduced PRODUCT_CHECK_PREBUILT_MAX_PAGE_SIZE which
# validates that prebuilt vendor libraries have load segments aligned to >=
# 16 KB. Some prebuilts in upstream AOSP (notably prebuilts/misc/protobuf_
# vendorcompat/) were compiled with 4 KB max-page-size and haven't been
# updated for the 16 KB requirement.
#
# The check is advisory: kernels handle 4 KB-aligned segments within 16 KB
# regions transparently. Bypassing the check has no functional impact at
# runtime; it only suppresses build-time warnings about inefficient memory
# packing on 16 KB page systems.
#
# AOSP documents this bypass directly in check_elf_file's error message:
#   "Device mk: PRODUCT_CHECK_PREBUILT_MAX_PAGE_SIZE := false"
#
# Affected prebuilts in our build (verified iter 205):
#   prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-lite-21.12.so
#   prebuilts/misc/protobuf_vendorcompat/arm64/libprotobuf-cpp-full-21.12.so
#   plus 6 more older / 32-bit variants in same dir (8 total potentially affected)
#
# Dodge sm8750-common doesn't trip this check (verified iter 205) — likely
# because their PRODUCT_PACKAGES doesn't pull in libprotobuf-cpp-*-vendorcompat.
# We pull them in via some closure-related package; identifying the parent
# is post-build investigation work, not blocking. Bypass is the documented
# AOSP mechanism regardless.
PRODUCT_CHECK_PREBUILT_MAX_PAGE_SIZE := false
