# AUTO-GENERATED by device/nubia/NX809J/closure.py.
# Do not edit by hand — re-run closure.py to regenerate.
#
# PRODUCT_COPY_FILES rules for files under PCF_BYPASS_PATHS
# prefixes in closure.py. These bypass extract-utils + Soong
# entirely (Make-level install). See closure.py for the
# per-prefix rationale.

# vendor/etc/ — 78 files
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/IDP_UPD/IDP_UPD_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP_UPD/IDP_UPD_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_cdp/CDP_alor_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_cdp/CDP_alor_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_cdp/CDP_alor_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_cdp/CDP_alor_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_mtp_wcd9378/MTP_alor_wcd9378_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_mtp_wcd9378/MTP_alor_wcd9378_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_mtp_wcd9378/MTP_alor_wcd9378_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_mtp_wcd9378/MTP_alor_wcd9378_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_mtp_wcd939x/MTP_alor_wcd939x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_mtp_wcd939x/MTP_alor_wcd939x_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_mtp_wcd939x/MTP_alor_wcd939x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_mtp_wcd939x/MTP_alor_wcd939x_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_qrd/QRD_alor_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_qrd/QRD_alor_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/alor_qrd/QRD_alor_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/alor_qrd/QRD_alor_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_atp/ATP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_atp/ATP_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_atp/ATP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_atp/ATP_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp/CDP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp/CDP_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp/CDP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp/CDP_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp/MTP_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp/MTP_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_qrd/QRD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd/QRD_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_qrd/QRD_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd/QRD_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_acdb_cal.acdb \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_workspaceFileXml.qwsp \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/ffv__16.0.1.1_0.0__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__16.0.1.1_0.0__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/ffv__6.1.3_0.1__eai_5.6.0_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__6.1.3_0.1__eai_5.6.0_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.0.1_0.1__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.0.1_0.1__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.0.1_0.2__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.0.1_0.2__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.1.1_0.2__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.1.1_0.2__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/ffv_models/hk01b_relu_eAI_5.6_eNPU_V6_adsp_i.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/hk01b_relu_eAI_5.6_eNPU_V6_adsp_i.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/click.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/double_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/double_click.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/heavy_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/heavy_click.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/pop.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/pop.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_1.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_1.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_2.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_2.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_3.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_3.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_4.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_4.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_5.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_5.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_6.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_6.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_7.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_7.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/reserved_8.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_8.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/texture_tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/texture_tick.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/thud.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/thud.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tick.pcm \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_cdp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_cdp.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_mtp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_mtp.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_qrd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_rx_tuning_0_qrd.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_cdp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_cdp.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_mtp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_mtp.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_qrd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tuning_data/haptics_vi_tuning_0_qrd.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.20.0_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.20.0_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.1.46_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__11.0.0_0.0__eai_4.6.0_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.1.46_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__11.0.0_0.0__eai_4.6.0_enpuv5.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.60.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.60.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.60.1.0_2.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.60.1.0_2.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.16_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.16_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.21_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.21_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.21_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.21_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.3_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.3_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/ffv__14.0.1.1_0.0__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/ffv__14.0.1.1_0.0__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_ns_models/ffv__16.0.1.1_0.0__eai_5.6_enpu_v6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/ffv__16.0.1.1_0.0__eai_5.6_enpu_v6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_5.3.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_5.3.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_5.6.0_enpuv6.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_5.6.0_enpuv6.pmd \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/sdz_model/sdz_model.bin:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/sdz_model/sdz_model.bin \
    vendor/nubia/NX809J/proprietary/vendor/etc/acdbdata/wnr_models/wind_filter__1.0__48k__2ch__16b__eai_5.5.eai:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/wnr_models/wind_filter__1.0__48k__2ch__16b__eai_5.5.eai

# vendor/qprof/ — 21 files
PRODUCT_COPY_FILES += \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/command-handlers/libQualcommProfilerEtmSyncCommandHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/command-handlers/libQualcommProfilerEtmSyncCommandHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/command-handlers/libQualcommProfilerHWInfoSyncCommandHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/command-handlers/libQualcommProfilerHWInfoSyncCommandHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerCpuHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerCpuHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerGpuProfilingHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerGpuProfilingHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerIoHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerIoHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerLaBwProfHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerLaBwProfHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerMemHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerMemHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerPowerHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerPowerHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerProcessHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerProcessHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerSysmonProfilingHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerSysmonProfilingHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerSysmonStatsHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerSysmonStatsHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/handlers/libQualcommProfilerThermalHandler.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/handlers/libQualcommProfilerThermalHandler.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libDSPTestLA.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libDSPTestLA.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libGPUProf.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libGPUProf.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libProfileCMetaSharedLib.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libProfileCMetaSharedLib.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libQualcommProfilerApi.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libQualcommProfilerApi.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libQualcommProfilerCore.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libQualcommProfilerCore.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libQualcommProfilerQLog.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libQualcommProfilerQLog.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libQualcommProfilerTraceRouter.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libQualcommProfilerTraceRouter.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/libs/libsysmonapps.so:$(TARGET_COPY_OUT_VENDOR)/qprof/libs/libsysmonapps.so \
    vendor/nubia/NX809J/proprietary/vendor/qprof/verison.txt:$(TARGET_COPY_OUT_VENDOR)/qprof/verison.txt

